# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "ehci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/30d1ad3d-9319-491b-90c3-b8e69851eb58";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-ebb5b0fa-3a3b-4320-bf5c-7656eed83aca".device =
    "/dev/disk/by-uuid/ebb5b0fa-3a3b-4320-bf5c-7656eed83aca";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/AD7B-8E53";
    fsType = "vfat";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/5b4eec29-34f4-42cd-ac39-4e124fa5c0df"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s25.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  services.fwupd.enable = true;
  services.openntpd.enable = true;
  #services.ntp.enable = true;
  services.fstrim.enable = true;

  # Enable OpenGL
  hardware.opengl.enable = true;
  hardware.opengl.driSupport = true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
