# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9587aa9c-dbaf-4dac-bcb8-402c1c307f23";
      fsType = "btrfs";
      options = [ "subvol=@" "noatime" "compress-force=zstd:1"];
    };

  boot.initrd.luks.devices."luks-c13e2cb8-b419-4cfd-a01a-381725aeca2f".device = "/dev/disk/by-uuid/c13e2cb8-b419-4cfd-a01a-381725aeca2f";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/ca39269a-878f-41e4-ac46-42e99b65ea6d"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s25.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

 zramSwap = {
    enable = true;
    algorithm = "zstd";
  };

  time.hardwareClockInLocalTime = true;
  services.ntp.enable = true;
  services.fstrim.enable = true;
  powerManagement.powertop.enable = true;
  hardware.opengl.enable = true;
  hardware.opengl.driSupport = true;

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
